sources:
  - name: source
    database: DBT_YT  
    schema: source 
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_date 
      - name: dim_store 
      - name: dim_product
      - name: dim_customer
